[package]
name = "campsite-tracker"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "campsite-tracker"
path = "src/main.rs"

[lib]
name = "campsite_tracker"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0"
actix-web = "4.4"
actix-files = "0.6"
tokio = "1.45"
reqwest = { version = "0.12.19", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
urlencoding = "2.1"
